"""
Report Service — generates professional SOC PDF and CSV reports and manages report downloads.
"""

from __future__ import annotations

import csv
import io
import logging
import os
import uuid
from typing import Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.core.exceptions import NotFoundError
from app.models.enums import ReportType
from app.models.report import Report
from app.models.user import User
from app.repositories.alert_repository import AlertRepository
from app.repositories.incident_repository import IncidentRepository
from app.repositories.report_repository import ReportRepository
from app.repositories.risk_repository import RiskRepository
from app.schemas.report import ReportGenerateRequest, ReportOut
from app.utils.datetime_utils import utc_now

logger = logging.getLogger(__name__)

REPORT_UPLOAD_DIR = "uploads/reports"


class ReportService:
    def __init__(
        self,
        report_repository: ReportRepository,
        alert_repository: AlertRepository,
        incident_repository: IncidentRepository,
        risk_repository: RiskRepository,
    ):
        self.report_repository = report_repository
        self.alert_repository = alert_repository
        self.incident_repository = incident_repository
        self.risk_repository = risk_repository
        os.makedirs(REPORT_UPLOAD_DIR, exist_ok=True)

    def generate_report(self, data: ReportGenerateRequest, user: User) -> ReportOut:
        now = utc_now()
        timestamp_str = now.strftime("%Y%m%d_%H%M%S")
        sanitized_name = "".join(c for c in data.report_name if c.isalnum() or c in ("-", "_")).strip() or "soc_report"
        
        if data.report_type == ReportType.CSV:
            filename = f"{sanitized_name}_{timestamp_str}.csv"
            filepath = os.path.join(REPORT_UPLOAD_DIR, filename)
            self._generate_csv(filepath)
        else:
            filename = f"{sanitized_name}_{timestamp_str}.pdf"
            filepath = os.path.join(REPORT_UPLOAD_DIR, filename)
            self._generate_pdf(filepath, data.report_name, user.username)

        report = Report(
            id=uuid.uuid4(),
            report_name=data.report_name,
            report_type=data.report_type,
            generated_at=now,
            file_path=filepath,
            generated_by_id=user.id,
        )
        self.report_repository.create(report)

        return ReportOut(
            id=report.id,
            report_name=report.report_name,
            report_type=report.report_type,
            generated_at=report.generated_at,
            file_path=report.file_path,
            generated_by_id=report.generated_by_id,
        )

    def _generate_csv(self, filepath: str) -> None:
        alerts, _ = self.alert_repository.search(limit=1000)
        with open(filepath, mode="w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow([
                "Alert ID", "Title", "Severity", "Status", "Risk Score", "Created At"
            ])
            for a in alerts:
                score = a.risk_assessment.risk_score if a.risk_assessment else "N/A"
                writer.writerow([
                    str(a.id),
                    a.title,
                    a.severity.value if hasattr(a.severity, "value") else str(a.severity),
                    a.status.value if hasattr(a.status, "value") else str(a.status),
                    score,
                    a.created_at.isoformat() if a.created_at else "",
                ])

    def _generate_pdf(self, filepath: str, title: str, author: str) -> None:
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0f172a"),
        )
        elements.append(Paragraph(f"Autonomous SOC Analyst — {title}", title_style))
        elements.append(Spacer(1, 10))

        # Metadata
        meta_text = f"<b>Generated By:</b> {author} &nbsp;|&nbsp; <b>Timestamp:</b> {utc_now().strftime('%Y-%m-%d %H:%M UTC')}"
        elements.append(Paragraph(meta_text, styles["Normal"]))
        elements.append(Spacer(1, 15))

        # Metrics Overview
        alert_stats = self.alert_repository.get_statistics()
        incident_stats = self.incident_repository.get_statistics()
        risk_stats = self.risk_repository.get_statistics()

        overview_data = [
            ["Metric", "Value", "Status / Notes"],
            ["Total Alerts Tracked", str(alert_stats.get("total_alerts", 0)), "Active telemetry events"],
            ["Critical Open Alerts", str(alert_stats.get("critical_open", 0)), "Requires immediate containment"],
            ["Open Incidents", str(incident_stats.get("open_active_incidents", 0)), "Ongoing SOC investigations"],
            ["Average Threat Risk Score", f"{risk_stats.get('average_risk_score', 0.0)} / 100", "Calculated deterministic risk"],
        ]

        t = Table(overview_data, colWidths=[200, 100, 240])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Recent Alerts Section
        elements.append(Paragraph("<b>Recent High-Priority Alert Telemetry</b>", styles["Heading2"]))
        elements.append(Spacer(1, 8))

        alerts, _ = self.alert_repository.search(limit=8)
        alert_rows = [["Title", "Severity", "Status", "Date"]]
        for a in alerts:
            sev = a.severity.value.upper() if hasattr(a.severity, "value") else str(a.severity)
            st = a.status.value.upper() if hasattr(a.status, "value") else str(a.status)
            dt = a.created_at.strftime("%m-%d %H:%M") if a.created_at else ""
            alert_rows.append([a.title[:40], sev, st, dt])

        if len(alert_rows) == 1:
            alert_rows.append(["No alerts currently recorded", "-", "-", "-"])

        t2 = Table(alert_rows, colWidths=[240, 90, 110, 100])
        t2.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        elements.append(t2)

        doc.build(elements)

    def list_reports(
        self,
        report_type: ReportType | None = None,
        skip: int = 0,
        limit: int = 50,
    ) -> tuple[list[ReportOut], int]:
        reports, total = self.report_repository.list_reports(
            report_type=report_type, skip=skip, limit=limit
        )
        return [
            ReportOut(
                id=r.id,
                report_name=r.report_name,
                report_type=r.report_type,
                generated_at=r.generated_at,
                file_path=r.file_path,
                generated_by_id=r.generated_by_id,
            )
            for r in reports
        ], total

    def get_report_or_404(self, report_id: uuid.UUID) -> Report:
        report = self.report_repository.get_by_id(report_id)
        if not report or report.deleted_at is not None:
            raise NotFoundError(f"Report '{report_id}' not found.")
        return report
